server:
  port: 9002
spring:
  thymeleaf:
    mode: LEGACYHTML5
  activemq:
      broker-url: tcp://127.0.0.1:61617
      user: admin
      password: admin
      in-memory: true
      # 如果此处设置为true，需要加activemq-pool的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      pool:
        enabled: false



